updated

diff --git a/vcedit b/vcedit
--- a/vcedit
+++ b/vcedit
@@ -63,8 +63,8 @@ vcinit ()
             while [ $VALID_RESPONSE == 0 ]
             do
                 echo -e "\033[34mDo you wish to continue? \033[0m"
-                echo -e "\033[34mYes \(Y\) \033[0m"
-                echo -e "\033[34mNo \(N\) \033[0m"
+                echo -e "\033[34mYes (Y) \033[0m"
+                echo -e "\033[34mNo (N) \033[0m"
                 read RESPONSE
                 case $RESPONSE in
                     Y|y|Yes|YES|yes)
@@ -236,8 +236,8 @@ then
             while [ $VALID_RESPONSE == 0 ]
             do
                 echo -e "\033[34mDo you wish to continue? \033[0m"
-                echo -e "\033[34mYes \(Y\) \033[0m"
-                echo -e "\033[34mNo \(N\) \033[0m"
+                echo -e "\033[34mYes (Y) \033[0m"
+                echo -e "\033[34mNo (N) \033[0m"
                 read RESPONSE
                 case $RESPONSE in
                     Y|y|Yes|YES|yes)
@@ -272,7 +272,7 @@ then
     fi
 fi
 
-if [ $NEWFILE ] 
+if [ $NEWFILE ] && [ ! $VCLIST ] && [ ! $VCINFO ] && [ ! $VCLOG ] 
 then
     if [ ! `svn --config-option config:tunnels:ssh="$SSHOPTS" status -u -v $NEWFILE | awk {'print $NF'} | grep $NEWFILE` ] 
     then
@@ -285,11 +285,12 @@ then
     fi
     else
         echo -e "\033[34mAn existing file of the same name exists on the repository. The file will be exported to current working directory before editing. \033[0m"
+        VALID_RESPONSE=0
         while [ $VALID_RESPONSE == 0 ]
         do
             echo -e "\033[34mDo you wish to continue? \033[0m"
-            echo -e "\033[34mYes \(Y\) \033[0m"
-            echo -e "\033[34mNo \(N\) \033[0m"
+            echo -e "\033[34mYes (Y) \033[0m"
+            echo -e "\033[34mNo (N) \033[0m"
             read RESPONSE
             case $RESPONSE in
                 Y|y|Yes|YES|yes)
@@ -309,6 +310,8 @@ then
         done
         [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn update $NEWFILE \033[0m"
         svn --config-option config:tunnels:ssh="$SSHOPTS" update $NEWFILE
+        EDIT_FILE=`readlink -f $(dirname $NEWFILE)`/$(basename $NEWFILE)
+        unset NEWFILE
     fi
 fi
 
@@ -352,8 +355,8 @@ then
     echo Unable to retreive SVN status. 
     exit 1
 fi
-FILE_STATUS=(`svn status $EDIT_FILE -v | awk {'print $1,$NF'}`)
-#echo file status is ${FILE_STATUS[0]}
+FILE_STATUS=(`svn --config-option config:tunnels:ssh="$SSHOPTS" status -v $EDIT_FILE | awk {'print $1,$NF'}`)
+echo file $EDIT_FILE status is "${FILE_STATUS[0]}"
 if [ -z $FILE_STATUS ] 
 then
     echo 
@@ -361,7 +364,7 @@ then
     while [ $VALID_RESPONSE == 0 ]
     do
         echo -e "\033[34mWould you like to add the file $EDIT_FILE to revision control? \033[0m"
-        echo -e "\033[34mYes \(Y\) No \(N\) \033[0m"
+        echo -e "\033[34mYes (Y) No (N) \033[0m"
         read RESPONSE
         case $RESPONSE in
             Y|y|Yes|YES|yes)
@@ -381,7 +384,7 @@ then
                 ;;
             *)
                 echo
-                echo -e "\033[34mPlease specify "Yes" or "No" as answer only. \033[0m"
+                echo -e "\033[34mPlease specify \"Yes\" or \"No\" as answer only. \033[0m"
                 echo -e "\033[34mPlease retry. \033[0m"
                 echo
                 ;;
@@ -399,8 +402,8 @@ then
     VALID_RESPONSE=0
     while [ $VALID_RESPONSE == 0 ]
     do
-        echo Would you like to add the file \"$EDIT_FILE\" to revision control? 
-        echo Yes \(Y\) No \(N\)
+        echo -e "\033[34mWould you like to add the file \"$EDIT_FILE\" to revision control? \033[0m"
+        echo -e "\033[34mYes (Y) No (N) \033[0m"
         read RESPONSE
         case $RESPONSE in
             Y|y|Yes|YES|yes)
@@ -414,8 +417,8 @@ then
                 ;;
             *)
                 echo
-                echo Please specify "Yes" or "No" as answer only.
-                echo Please retry.
+                echo -e "\033[34mPlease specify \"Yes\" or \"No\" as answer only. \033[0m"
+                echo -e "\033[34mPlease retry. \033[0m"
                 echo
                 ;;
         esac  
@@ -424,11 +427,11 @@ elif [ "${FILE_STATUS[0]}" == "M" ]
 then
     while true
     do
-        echo File \"$EDIT_FILE\" has been modified but changes are not committed. 
-        echo Would you like to discard the changes and proceed to edit the file? 
-        echo Would you like to view the changes since the last commit? 
-        echo Would you like to include the changes and proceed to edit the file? 
-        echo Discard \(D\), View \(V\), Include \(I\)
+        echo -e "\033[34mFile \"$EDIT_FILE\" has been modified but changes are not committed. \033[0m"
+        echo -e "\033[34mWould you like to discard the changes and proceed to edit the file? \033[0m"
+        echo -e "\033[34mWould you like to view the changes since the last commit? \033[0m"
+        echo -e "\033[34mWould you like to include the changes and proceed to edit the file? \033]0m"
+        echo -e "\033[34mDiscard (D), View (V), Include (I) \033[0m"
         read RESPONSE
         case $RESPONSE in
             D)
@@ -443,8 +446,8 @@ then
                 ;;
             *)
                 echo
-                echo Please specify "D", "V" or "I" as answer only. 
-                echo Please retry. 
+                echo -e "\033[34mPlease specify \"D\", \"V\" or \"I\" as answer only. \033[0m"
+                echo -e "\033[34mPlease retry. \033[0m"
                 echo
                 ;;
         esac
@@ -463,7 +466,7 @@ case ${FILE_STATUS[0]} in
         while [ $VALID_RESPONSE == 0 ]
         do
             echo -e "\033[34mWould you like to add the file \"$EDIT_FILE\" to revision control? \033[0m"
-            echo -e "\033[34mYes \(Y\) No \(N\) \033[0m"
+            echo -e "\033[34mYes (Y) No (N) \033[0m"
             read RESPONSE
             case $RESPONSE in
                 Y|y|Yes|YES|yes)
@@ -487,11 +490,11 @@ case ${FILE_STATUS[0]} in
     M)
         while true
         do
-            echo "\033[34mFile \"$EDIT_FILE\" has been modified but changes are not committed. \033[0m"
-            echo "\033[34mWould you like to discard the changes and proceed to edit the file? \033[0m"
-            echo "\033[34mWould you like to view the changes since the last commit? \033[0m"
-            echo "\033[34mWould you like to include the changes and proceed to edit the file? \033[0m"
-            echo "\033[34mDiscard \(D\), View \(V\), Include \(I\) \033[0m"
+            echo -e "\033[34mFile \"$EDIT_FILE\" has been modified but changes are not committed. \033[0m"
+            echo -e "\033[34mWould you like to discard the changes and proceed to edit the file? \033[0m"
+            echo -e "\033[34mWould you like to view the changes since the last commit? \033[0m"
+            echo -e "\033[34mWould you like to include the changes and proceed to edit the file? \033[0m"
+            echo -e "\033[34mDiscard \(D\), View \(V\), Include \(I\) \033[0m"
             read RESPONSE
             case $RESPONSE in
                 D)
@@ -515,13 +518,53 @@ case ${FILE_STATUS[0]} in
         ;;
 esac
 
-[ $VCDEBUG ] && echo "\033[34mExecuting: svn lock $EDIT_FILE \033[0m"
+[ $VCDEBUG ] && echo -e "\033[34mExecuting: svn lock $EDIT_FILE \033[0m"
 svn --config-option config:tunnels:ssh="$SSHOPTS" lock $EDIT_FILE
 if [ $? != 0 ]
 then
-    echo -e "\033[34mCannot obtain lock on $EDIT_FILE. \033[0m"
-    svn revert $EDIT_FILE
-    exit 1
+    [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn lock $EDIT_FILE \033[0m"
+    svn --config-option config:tunnels:ssh="$SSHOPTS" lock $EDIT_FILE 2>&1 | grep "Lock failed: newer version" > /dev/null
+    if [ $? == 0 ]
+    then
+        echo -e "\033[34mAn updated version of the file is available from remote repository. \033[0m"
+        echo -e "\033[34mThe updated file will be exported to the current working directory. \033[0m"
+        VALID_RESPONSE=0
+        while [ $VALID_RESPONSE == 0 ]
+        do
+            echo -e "\033[34mDo you wish to continue? \033[0m"
+            echo -e "\033[34mYes (Y) \033[0m"
+            echo -e "\033[34mNo (N) \033[0m"
+            read RESPONSE
+            case $RESPONSE in
+                Y|y|Yes|YES|yes)
+                    VALID_RESPONSE=1
+                    ;;
+                N|n|No|NO|no)
+                    VALID_RESPONSE=1
+                    exit 0
+                    ;;
+                *)
+                    echo
+                    echo -e "\033[31mPlease specify \033[47;31mYes\033[31m or \033[47;31mNo\033[31m as answer only. \033[0m"
+                    echo -e "\033[31mPlease retry. \033[0m"
+                    echo
+                    ;;
+            esac
+        done
+        [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn update $EDIT_FILE \033[0m"
+        svn --config-option config:tunnels:ssh="$SSHOPTS" update $EDIT_FILE
+        [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn lock $EDIT_FILE \033[0m"
+        svn --config-option config:tunnels:ssh="$SSHOPTS" lock $EDIT_FILE
+        if [ $? != 0 ]
+        then
+            echo -e "\033[34mCannot obtain lock on $EDIT_FILE. \033[0m"
+            exit 1
+        fi
+    else
+        echo -e "\033[34mCannot obtain lock on $EDIT_FILE. \033[0m"
+        svn revert $EDIT_FILE
+        exit 1
+    fi
 fi
 [[ ! $NEWFILE ]] && vi $EDIT_FILE
 NUM_DIFF=`svn diff ${EDIT_FILE}|wc -l`
@@ -533,7 +576,7 @@ then
     svn --config-option config:tunnels:ssh="$SSHOPTS" ci ${EDIT_FILE} -m "$USERNAME: $COMMENT" 
 else
     echo -e "\033[34mNo change made on $EDIT_FILE \033[0m"
-    [ $VCDEBUG ] && echo "\033[34mExecuting: svn unlock $EDIT_FILE \033[0m"
+    [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn unlock $EDIT_FILE \033[0m"
     svn --config-option config:tunnels:ssh="$SSHOPTS" unlock $EDIT_FILE
 fi
 
