enhancements

diff --git a/vcedit b/vcedit
--- a/vcedit
+++ b/vcedit
@@ -355,7 +355,7 @@ then
     echo Unable to retreive SVN status. 
     exit 1
 fi
-FILE_STATUS=($(echo \\`svn --config-option config:tunnels:ssh="$SSHOPTS" status -u -v $EDIT_FILE | grep $EDIT_FILE | awk {'print $1,$NF'}`))
+FILE_STATUS=`svn --config-option config:tunnels:ssh="$SSHOPTS" status -u -v $EDIT_FILE | grep $EDIT_FILE | awk {'print $1,$NF'}`
 if [ -z $FILE_STATUS ] 
 then
     echo 
@@ -453,7 +453,108 @@ then
     done
 fi
 DEPRECATED
+if [ "`echo "$FILE_STATUS" | grep ^?`" ]
+then
+    echo -e "\033[34mFile \"$EDIT_FILE\" is not under revision control. \033[0m"
+    VALID_RESPONSE=0
+    while [ $VALID_RESPONSE == 0 ]
+    do
+        echo -e "\033[34mWould you like to add the file \"$EDIT_FILE\" to revision control? \033[0m"
+        echo -e "\033[34mYes (Y) No (N) \033[0m"
+        read RESPONSE
+        case $RESPONSE in
+            Y|y|Yes|YES|yes)
+                VALID_RESPONSE=1
+                vcinit add $EDIT_FILE
+                ;;
+            N|n|No|NO|no)
+                VALID_RESPONSE=1
+                [[ ! $NEWFILE ]] && vi $EDIT_FILE
+                exit 0
+                ;;
+            *)
+                echo
+                echo -e "\033[34mPlease specify "Yes" or "No" as answer only. \033[0m"
+                echo -e "\033[34mPlease retry. \033[0m"
+                echo
+                ;;
+        esac
+    done
+fi
+
+if [ "`echo "$FILE_STATUS" | grep \*`" ]
+then
+    echo -e "\033[34mAn existing file of the same name exists on the repository. The file will be exported to current working directory before editing. \033[0m"
+    VALID_RESPONSE=0
+    while [ $VALID_RESPONSE == 0 ]
+    do
+        echo -e "\033[34mDo you wish to continue? \033[0m"
+        echo -e "\033[34mYes (Y) \033[0m"
+        echo -e "\033[34mNo (N) \033[0m"
+        read RESPONSE
+        case $RESPONSE in
+            Y|y|Yes|YES|yes)
+                VALID_RESPONSE=1
+                ;;
+            N|n|No|NO|no)
+                VALID_RESPONSE=1
+                exit 0
+                ;;
+            *)
+                echo
+                echo -e "\033[31mPlease specify \033[47;31mYes\033[31m or \033[47;31mNo\033[31m as answer only. \033[0m"
+                echo -e "\033[31mPlease retry. \033[0m"
+                echo
+                ;;
+        esac
+    done
+    [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn update $NEWFILE \033[0m"
+    svn --config-option config:tunnels:ssh="$SSHOPTS" update $NEWFILE
+fi
+
+if [ "`echo "$FILE_STATUS" | grep ^M`" ]
+then
+    while true
+    do
+        echo -e "\033[34mFile \"$EDIT_FILE\" has been modified but changes are not committed. \033[0m"
+        echo -e "\033[34mPress \"D\" to discard the changes and proceed to edit the file. \033[0m"
+        echo -e "\033[34mPress \"V\" to view the changes since the last commit. \033[0m"
+        echo -e "\033[34mPress \"I\" to include the changes and proceed to edit the file. \033[0m"
+        echo -e "\033[34mPress \"A\" to abort. \033[0m"
+        echo -e "\033[34mDo you want to Discard (D), View (V), Include (I), Abort (A)? \033[0m"
+        read RESPONSE
+        case $RESPONSE in
+            A)
+                exit 0
+                ;;
+            D)
+                svn revert $EDIT_FILE
+                break
+                ;;
+            V)
+                svn diff $EDIT_FILE
+                ;;
+            I)
+                break
+                ;;
+            *)
+                echo
+                echo "\033[34mPlease specify \"D\", \"V\", \"I\" or \"A\" as answer only. \033[0m"
+                echo "\033[34mPlease retry. \033[0m"
+                echo
+                ;;
+        esac
+    done
+fi
+
+if [ "`\echo "$FILE_STATUS" | grep ' K '`" ]
+then
+    echo -e "\033[34mFile \"$EDIT_FILE\" is currently locked and being edited by user $(echo "$FILE_STATUS" | awk {'print $(NF-1)'}). \033[0m"
+    exit 1
+fi
+
 echo file $EDIT_FILE status is "${FILE_STATUS[0]}"
+<<DEPRECATED
 case ${FILE_STATUS[0]} in
     \K)
         echo -e "\033[34mFile \"$EDIT_FILE\" is currently locked and being edited by user \"${FILE_STATUS[1]}\". \033[0m"
@@ -543,11 +644,15 @@ case ${FILE_STATUS[0]} in
         [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn update $NEWFILE \033[0m"
         svn --config-option config:tunnels:ssh="$SSHOPTS" update $NEWFILE
 esac
+DEPRECATED
 
 [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn lock $EDIT_FILE \033[0m"
 svn --config-option config:tunnels:ssh="$SSHOPTS" lock $EDIT_FILE
 if [ $? != 0 ]
 then
+    echo -e "\033[34mCannot obtain lock on $EDIT_FILE. \033[0m"
+    exit 1
+<<DEPRECATED
     [ $VCDEBUG ] && echo -e "\033[34mExecuting: svn lock $EDIT_FILE \033[0m"
     svn --config-option config:tunnels:ssh="$SSHOPTS" lock $EDIT_FILE 2>&1 | grep -E "Lock failed: newer version|File already exists" > /dev/null
     if [ $? == 0 ]
@@ -591,6 +696,7 @@ then
         svn revert $EDIT_FILE
         exit 1
     fi
+DEPRECATED
 fi
 [[ ! $NEWFILE ]] && vi $EDIT_FILE
 NUM_DIFF=`svn diff ${EDIT_FILE}|wc -l`
